language: android
jdk: oraclejdk8
sudo: required

android:
        components:
                - platform-tools
                - tools
                - build-tools-24.0.2
                - android-24
                - extra-android-m2repository
        licenses:
                - android-sdk-preview-license-52d11cd2
                - android-sdk-license-.+
                - google-gdk-license-.+
script:
        - ./gradlew build
before_install:
        - chmod +x gradlew
branches:
        only:
                - master
